import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
from reportlab.platypus import BaseDocTemplate, PageTemplate, Frame


# Brand Colors
GREEN_DARK   = colors.HexColor("#1a7a4a")
GREEN_MID    = colors.HexColor("#22a05b")
GREEN_LIGHT  = colors.HexColor("#d4f0e0")
GREEN_ACCENT = colors.HexColor("#4ade80")
BLACK        = colors.HexColor("#0d0d0d")
GRAY_900     = colors.HexColor("#111827")
GRAY_700     = colors.HexColor("#374151")
GRAY_500     = colors.HexColor("#6b7280")
GRAY_200     = colors.HexColor("#e5e7eb")
GRAY_100     = colors.HexColor("#f9fafb")
WHITE        = colors.HexColor("#ffffff")
RED_LIGHT    = colors.HexColor("#fee2e2")
RED_MID      = colors.HexColor("#ef4444")
SELECTED_BG  = colors.HexColor("#dcfce7")
REJECTED_BG  = colors.HexColor("#fee2e2")


def draw_header(c, doc, score, selected):
    w, h = A4
    # Dark header band
    c.setFillColor(GRAY_900)
    c.rect(0, h - 52*mm, w, 52*mm, fill=1, stroke=0)

    # Brand name
    c.setFillColor(GREEN_ACCENT)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(14*mm, h - 16*mm, "RECRUITMENT AI AGENT")

    # Tagline
    c.setFillColor(GRAY_500)
    c.setFont("Helvetica", 8)
    c.drawString(14*mm, h - 23*mm, "AI-Powered Resume Analysis Platform")

    # Date on right
    c.setFillColor(GRAY_500)
    c.setFont("Helvetica", 8)
    date_str = datetime.now().strftime("%B %d, %Y")
    c.drawRightString(w - 14*mm, h - 16*mm, date_str)
    c.drawRightString(w - 14*mm, h - 23*mm, "Confidential Report")

    # Score circle area
    cx = w - 35*mm
    cy = h - 40*mm
    radius = 12*mm

    c.setFillColor(GREEN_DARK)
    c.circle(cx, cy, radius, fill=1, stroke=0)

    c.setFillColor(WHITE)
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(cx, cy - 3*mm, str(score))
    c.setFont("Helvetica", 7)
    c.drawCentredString(cx, cy - 8*mm, "/ 100")

    # Verdict badge
    badge_color = GREEN_MID if selected else RED_MID
    verdict_text = "SELECTED" if selected else "NOT SELECTED"
    c.setFillColor(badge_color)
    c.roundRect(14*mm, h - 44*mm, 36*mm, 8*mm, 2*mm, fill=1, stroke=0)
    c.setFillColor(WHITE)
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(14*mm + 18*mm, h - 38.5*mm, verdict_text)

    # Cutoff note
    c.setFillColor(GRAY_500)
    c.setFont("Helvetica", 7)
    c.drawString(54*mm, h - 40*mm, "Cutoff: 75/100")


def draw_footer(c, doc):
    w, h = A4
    c.setFillColor(GRAY_200)
    c.rect(0, 0, w, 12*mm, fill=1, stroke=0)
    c.setFillColor(GRAY_500)
    c.setFont("Helvetica", 7)
    c.drawString(14*mm, 4.5*mm, "Generated by Recruitment AI Agent  •  Powered by Groq LLaMA 3.3")
    c.drawRightString(w - 14*mm, 4.5*mm, f"Page {doc.page}")


class ReportCanvas(canvas.Canvas):
    def __init__(self, *args, score=80, selected=True, **kwargs):
        super().__init__(*args, **kwargs)
        self._score = score
        self._selected = selected
        self._doc = None

    def showPage(self):
        self._draw_decorations()
        super().showPage()

    def save(self):
        self._draw_decorations()
        super().save()

    def _draw_decorations(self):
        w, h = A4
        # Header
        draw_header(self, self._doc, self._score, self._selected)
        # Footer
        draw_footer(self, self._doc)


def score_bar_table(score):
    """Draw a visual score progress bar using a table."""
    filled = int(score)
    empty = 100 - filled

    bar_color = GREEN_MID if score >= 75 else RED_MID

    data = [[""] * 100]
    col_widths = [1.5*mm] * 100

    style = [
        ('BACKGROUND', (0, 0), (filled - 1, 0), bar_color),
        ('BACKGROUND', (filled, 0), (99, 0), GRAY_200),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [None]),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
    ]

    t = Table(data, colWidths=col_widths, rowHeights=[6*mm])
    t.setStyle(TableStyle(style))
    return t


def skills_table(strengths, weaknesses):
    """Two-column table for strengths and weaknesses."""
    max_len = max(len(strengths), len(weaknesses), 1)

    data = [
        [
            Paragraph("<b>✓  Strengths</b>", ParagraphStyle('sh', fontName='Helvetica-Bold', fontSize=9, textColor=GREEN_DARK)),
            Paragraph("<b>✗  Missing Skills</b>", ParagraphStyle('sh', fontName='Helvetica-Bold', fontSize=9, textColor=RED_MID)),
        ]
    ]

    for i in range(max_len):
        s = strengths[i] if i < len(strengths) else ""
        w = weaknesses[i] if i < len(weaknesses) else ""

        s_para = Paragraph(f"• {s}", ParagraphStyle('sp', fontName='Helvetica', fontSize=8.5, textColor=GRAY_700, leftIndent=4)) if s else Paragraph("", ParagraphStyle('sp'))
        w_para = Paragraph(f"• {w}", ParagraphStyle('wp', fontName='Helvetica', fontSize=8.5, textColor=GRAY_700, leftIndent=4)) if w else Paragraph("", ParagraphStyle('wp'))

        data.append([s_para, w_para])

    w_total = 182*mm
    col_w = w_total / 2

    t = Table(data, colWidths=[col_w, col_w])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), SELECTED_BG),
        ('BACKGROUND', (1, 0), (1, 0), RED_LIGHT),
        ('BACKGROUND', (0, 1), (0, -1), colors.HexColor("#f0fdf4")),
        ('BACKGROUND', (1, 1), (1, -1), colors.HexColor("#fff5f5")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, GRAY_200),
        ('ROUNDEDCORNERS', [4]),
    ]))
    return t


def generate_pdf_report(score, selected, strengths, weaknesses, total_skills):
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=58*mm,
        bottomMargin=18*mm,
        leftMargin=14*mm,
        rightMargin=14*mm,
    )

    # Styles
    title_style = ParagraphStyle('Title', fontName='Helvetica-Bold', fontSize=18,
                                  textColor=GRAY_900, spaceAfter=2*mm)
    subtitle_style = ParagraphStyle('Subtitle', fontName='Helvetica', fontSize=10,
                                     textColor=GRAY_500, spaceAfter=6*mm)
    section_style = ParagraphStyle('Section', fontName='Helvetica-Bold', fontSize=11,
                                    textColor=GRAY_900, spaceBefore=6*mm, spaceAfter=3*mm)
    body_style = ParagraphStyle('Body', fontName='Helvetica', fontSize=9,
                                 textColor=GRAY_700, leading=14, spaceAfter=3*mm)
    small_style = ParagraphStyle('Small', fontName='Helvetica', fontSize=8,
                                  textColor=GRAY_500, spaceAfter=2*mm)

    story = []

    # Title section
    story.append(Paragraph("Resume Analysis Report", title_style))
    story.append(Paragraph("Comprehensive skill assessment and ATS compatibility analysis", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=GRAY_200))
    story.append(Spacer(1, 4*mm))

    # Score overview
    story.append(Paragraph("Score Overview", section_style))

    verdict_color = GREEN_MID if selected else RED_MID
    verdict_label = "SELECTED — Above cutoff threshold" if selected else "NOT SELECTED — Below cutoff threshold"

    score_summary_data = [
        [
            Paragraph(f"<b>{score}</b>", ParagraphStyle('sc', fontName='Helvetica-Bold', fontSize=28, textColor=GREEN_DARK if selected else RED_MID, alignment=TA_CENTER)),
            Paragraph(f"<b>out of 100</b><br/><font size=8 color='gray'>Cutoff: 75/100</font>", ParagraphStyle('sc2', fontName='Helvetica', fontSize=10, textColor=GRAY_700, leading=14)),
            Paragraph(f"<b>{len(strengths)}</b>", ParagraphStyle('sc3', fontName='Helvetica-Bold', fontSize=22, textColor=GREEN_DARK, alignment=TA_CENTER)),
            Paragraph("<b>Matched</b><br/><font size=8 color='gray'>Skills found</font>", ParagraphStyle('sc4', fontName='Helvetica', fontSize=10, textColor=GRAY_700, leading=14)),
            Paragraph(f"<b>{len(weaknesses)}</b>", ParagraphStyle('sc5', fontName='Helvetica-Bold', fontSize=22, textColor=RED_MID, alignment=TA_CENTER)),
            Paragraph("<b>Missing</b><br/><font size=8 color='gray'>Skills not found</font>", ParagraphStyle('sc6', fontName='Helvetica', fontSize=10, textColor=GRAY_700, leading=14)),
        ]
    ]

    score_table = Table(score_summary_data, colWidths=[20*mm, 40*mm, 20*mm, 40*mm, 20*mm, 42*mm])
    score_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (0, 0), 'CENTER'),
        ('ALIGN', (2, 0), (2, 0), 'CENTER'),
        ('ALIGN', (4, 0), (4, 0), 'CENTER'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('BACKGROUND', (0, 0), (-1, -1), GRAY_100),
        ('BOX', (0, 0), (-1, -1), 0.5, GRAY_200),
        ('LINEAFTER', (1, 0), (1, 0), 0.5, GRAY_200),
        ('LINEAFTER', (3, 0), (3, 0), 0.5, GRAY_200),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 3*mm))

    # Score bar
    story.append(Paragraph("ATS Compatibility Score", small_style))
    story.append(score_bar_table(score))
    story.append(Paragraph(f"{score}% match with required skills", ParagraphStyle('pct', fontName='Helvetica', fontSize=8, textColor=GRAY_500, alignment=TA_RIGHT)))
    story.append(Spacer(1, 4*mm))

    # Verdict
    verdict_bg = SELECTED_BG if selected else RED_LIGHT
    verdict_data = [[
        Paragraph(
            f"<b>{'✓' if selected else '✗'}  Final Verdict: {verdict_label}</b>",
            ParagraphStyle('vd', fontName='Helvetica-Bold', fontSize=10,
                           textColor=GREEN_DARK if selected else RED_MID)
        )
    ]]
    verdict_table = Table(verdict_data, colWidths=[182*mm])
    verdict_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), verdict_bg),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('BOX', (0, 0), (-1, -1), 0.5, GREEN_MID if selected else RED_MID),
    ]))
    story.append(verdict_table)
    story.append(Spacer(1, 5*mm))

    # Skills breakdown
    story.append(HRFlowable(width="100%", thickness=1, color=GRAY_200))
    story.append(Paragraph("Skills Breakdown", section_style))
    story.append(skills_table(strengths, weaknesses))
    story.append(Spacer(1, 5*mm))

    # Recommendations
    story.append(HRFlowable(width="100%", thickness=1, color=GRAY_200))
    story.append(Paragraph("Recommendations", section_style))

    if selected:
        rec_text = (
            "This candidate demonstrates a strong match with the required skill set. "
            "The resume shows proficiency in most of the key areas evaluated. "
            "We recommend proceeding to the interview stage."
        )
    else:
        missing_str = ", ".join(weaknesses[:5]) if weaknesses else "various key areas"
        rec_text = (
            f"This candidate's resume does not meet the minimum threshold of 75/100. "
            f"Key gaps identified include: <b>{missing_str}</b>. "
            f"The candidate should strengthen these areas before reapplying, or consider roles "
            f"that better align with their current skill set."
        )

    story.append(Paragraph(rec_text, body_style))
    story.append(Spacer(1, 3*mm))

    # Tips box
    tips_data = [[
        Paragraph(
            "<b>💡 Tips to Improve Your Score</b><br/>"
            "• Add missing skills to your resume if you have experience with them<br/>"
            "• Use industry-standard terminology for better ATS matching<br/>"
            "• Quantify achievements with numbers and percentages<br/>"
            "• Tailor your resume to each specific job description",
            ParagraphStyle('tips', fontName='Helvetica', fontSize=8.5, textColor=GRAY_700, leading=13)
        )
    ]]
    tips_table = Table(tips_data, colWidths=[182*mm])
    tips_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f0f9ff")),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#bae6fd")),
    ]))
    story.append(tips_table)

    # Build with custom canvas
    def make_canvas(*args, **kwargs):
        c = ReportCanvas(*args, score=score, selected=selected, **kwargs)
        c._doc = doc
        return c

    doc.build(story, canvasmaker=make_canvas)
    buffer.seek(0)
    return buffer.read()